baseurl = "/"
languageCode = "en-us"
title = "Concetta's Main Street Bistro"
theme = "strata"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Concetta's Main Street Bistro"
	description = "Located in historic downtown Mount Airy and open daily at 7:30. We invite you to stop in!"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Concetta's Main Street Bistro** <br> Located in historic downtown Mount Airy and open daily at 7:30. We invite you to stop in!"
		# The icons will be shown if you enter your username
		facebook = "Concettas-Mainstreet-Bistro-108116492564016"
		yelp = "concettas-main-steet-bistro-mount-airy"
		tripadvisor="Restaurant_Review-g41276-d2317412-Reviews-Concetta_s_Mainstreet_Bistro-Mount_Airy_Maryland.html"

		copyright = [
			"&copy; Concetta's Main Street Bistro",
		]


	[params.about]
		hide  = false
		title = "About Us"
		content = "Concetta's Main St Bistro, located in historic downtown Mt. Airy, opens daily at 7:30 with a complete breakfast & brunch menu. For lunch, enjoy one of our famously over stuffed sandwiches or subs. Our soups & salads our seasonal, fresh and \"Souper\" Calafrajgalistically delicious. In addition to daily chef inspired creations, customer creativity is welcome and encouraged. Just because you don't see it on our menu doesn't mean we can't make fresh for you. We invite you to stop in for breakfast, brunch, lunch or take home one of our unique oven ready dinners."


	[params.recentposts]
		hide  = false
		title = "Recent blog posts"


	[params.specials]
		hide  = false
		title = "Daily and Seasonal Specials"
		blurb = "Check here often, we always have something exciting happening!"


	[params.cuisine]
		hide  = false
		title = "Menu"
		blurb = "We pride ourselves in offering the freshest menu using the finest available meats and produce."


	[params.events]
		hide  = false
		title = "Events"
		blurb = "Check here often, we always have something exciting happening!"


	[params.photos]
		hide  = false
		title = "Photo Gallery"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.photos.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			description = "Image caption example"

		[[params.photos.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			description = "Image caption example"

		[[params.photos.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			description = "Image caption example"

		[[params.photos.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			description = "Image caption example"

		# [[params.photos.gallery]]
		# 	image = "fulls/05.jpg"
		# 	thumb = "thumbs/05.jpg"
		# 	description = "Image caption example"

		# [[params.photos.gallery]]
		# 	image = "fulls/06.jpg"
		# 	thumb = "thumbs/06.jpg"
		# 	description = "Image caption example"


	[params.catering]
		hide  = false
		title = "Catering"
		blurb = "We cater parties, weddings and banquets! Plan your event now!"


	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Call us anytime! If you have questions or comments, please share them with us below."

		# This can be exact coordinates or a searchable address in google maps
		# gmaps_address = "231 S Main St, Mt Airy, MD 21771"
		# address = [
			# "231 South Main Street",
			# "Mount Airy, MD 21771"
		# ]
		phone = "301-829-7571"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		# email = "concettas@verizon.net"
		email = "mail@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"

	[params.rss]
		hide = true
